# -*- coding: utf-8 -*-
"""CO2_Emission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zIQEuJTCEt7CwDXzWs5XVwmpGj7G5mmo
"""

import pandas as pd
url = "https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv"
df = pd.read_csv(url)

df_essentiel = df[["country", "iso_code", "year", "population", "gdp", "co2", "cumulative_co2", "co2_per_gdp", "coal_co2", "gas_co2",
                   "oil_co2", "flaring_co2", "cement_co2", "other_industry_co2", "energy_per_capita", "energy_per_gdp"]]

df_essentiel.duplicated().sum()
df_essentiel.drop_duplicates(inplace=True)
df_essentiel = df_essentiel[df_essentiel['co2'].notnull()]
df_essentiel = df_essentiel[df_essentiel['year'] >= 2000]

# supprimer les ligne contenant country like Africa, Asie, ...
regions = ["World", "Africa", "Asia", "Europe", "North America", "South America", "Oceania", "Israel"]
df_essentiel = df_essentiel[~df_essentiel["country"].isin(regions)]
df_essentiel = df_essentiel[~df_essentiel["country"].str.contains(r'\d|\(|\)|income|International')]

# Enlever les NaN
df_essentiel.loc[df_essentiel['population'].isna(), 'population']   = 0
df_essentiel.loc[df_essentiel['gdp'].isna(), 'gdp']                 = 0
df_essentiel.loc[df_essentiel['co2_per_gdp'].isna(), 'co2_per_gdp'] = 0
df_essentiel.loc[df_essentiel['coal_co2'].isna(), 'coal_co2']       = 0
df_essentiel.loc[df_essentiel['gas_co2'].isna(), 'gas_co2']         = 0
df_essentiel.loc[df_essentiel['oil_co2'].isna(), 'oil_co2']         = 0
df_essentiel.loc[df_essentiel['flaring_co2'].isna(), 'flaring_co2'] = 0
df_essentiel.loc[df_essentiel['cement_co2'].isna(), 'cement_co2']   = 0
df_essentiel.loc[df_essentiel['other_industry_co2'].isna(), 'other_industry_co2'] = 0

df_essentiel.loc[df_essentiel['energy_per_capita'].isna(), 'energy_per_capita'] = df_essentiel['energy_per_capita'].mean()
df_essentiel.loc[df_essentiel['energy_per_gdp'].isna(), 'energy_per_gdp']       = df_essentiel['energy_per_gdp'].mean()

df_essentiel.isna().sum()

df_essentiel['year'] = df_essentiel['year'].astype(int)
df_essentiel['population'] = pd.to_numeric(df_essentiel['population'], errors='coerce')
df_essentiel['co2'] = pd.to_numeric(df_essentiel['co2'], errors='coerce')

df_essentiel = df_essentiel.reset_index(drop=True)
print(df_essentiel.index)

for i in range(len(df_essentiel)-1) :
  if pd.isna(df_essentiel.loc[i, 'iso_code']):
    #print(df_essentiel.loc[i, 'country'][:3].upper())
    df_essentiel.loc[i, 'iso_code'] = df_essentiel.loc[i, 'country'][:3].upper()

df_essentiel.isna().sum()

# les emissions pour l'année 2023
df_2024 = df_essentiel[(df_essentiel["year"] == 2023) & (df_essentiel["co2"] >200)].sort_values(by="co2", ascending=False)
df_2024.plot(x="iso_code", y="co2", kind="bar")

df_essentiel.describe()

!pip install pymongo

# connection avec la base de données mongoDB
from pymongo import MongoClient
client = MongoClient("mongodb+srv://elhassnaouisalma_db_user:2020SalmaEL%402003@cluster0.ys9jin2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")

db = client['co2_db']
collection = db['co2_data']
collection.insert_many(df_essentiel.to_dict("records"))

df_essentiel.to_csv("co2_clean.csv", index=False)
from google.colab import files
files.download("co2_clean.csv")

from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://salma:salma123@cluster0.ys9jin2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

print(df_essentiel['co2'])

